export const ROLES = {
    ADMIN: 'admin',
    DOCTOR: 'doctor',
    NURSE: 'nurse',
    RECEPTION: 'reception',
    PATIENT: 'patient',
    PHARMACIST: 'pharmacist',
    LAB_TECHNICIAN: 'lab_technician'
};

export const PERMISSIONS = {
    MANAGE_USERS: 'manage_users',
    MANAGE_PATIENTS: 'manage_patients',
    MANAGE_APPOINTMENTS: 'manage_appointments',
    VIEW_PATIENTS: 'view_patients',
    VIEW_APPOINTMENTS: 'view_appointments',
    MANAGE_PHARMACIES: 'manage_pharmacies',
    MANAGE_LABORATORIES: 'manage_laboratories',
    VIEW_PHARMACIES: 'view_pharmacies',
    VIEW_LABORATORIES: 'view_laboratories'
};

export const ROLE_PERMISSIONS = {
    [ROLES.ADMIN]: [
        PERMISSIONS.MANAGE_USERS,
        PERMISSIONS.MANAGE_PATIENTS,
        PERMISSIONS.MANAGE_APPOINTMENTS,
        PERMISSIONS.VIEW_PATIENTS,
        PERMISSIONS.VIEW_APPOINTMENTS,
        PERMISSIONS.MANAGE_PHARMACIES,
        PERMISSIONS.MANAGE_LABORATORIES,
        PERMISSIONS.VIEW_PHARMACIES,
        PERMISSIONS.VIEW_LABORATORIES
    ],
    [ROLES.DOCTOR]: [
        PERMISSIONS.MANAGE_PATIENTS,
        PERMISSIONS.MANAGE_APPOINTMENTS,
        PERMISSIONS.VIEW_PATIENTS,
        PERMISSIONS.VIEW_APPOINTMENTS
    ],
    [ROLES.NURSE]: [
        PERMISSIONS.MANAGE_PATIENTS,
        PERMISSIONS.VIEW_PATIENTS,
        PERMISSIONS.VIEW_APPOINTMENTS
    ],
    [ROLES.RECEPTION]: [
        PERMISSIONS.MANAGE_APPOINTMENTS,
        PERMISSIONS.VIEW_APPOINTMENTS
    ],
    [ROLES.PATIENT]: [
        PERMISSIONS.VIEW_APPOINTMENTS
    ],
    [ROLES.PHARMACIST]: [
        PERMISSIONS.VIEW_PHARMACIES,
        PERMISSIONS.VIEW_PATIENTS // For prescription access
    ],
    [ROLES.LAB_TECHNICIAN]: [
        PERMISSIONS.VIEW_LABORATORIES,
        PERMISSIONS.VIEW_PATIENTS // For lab order access
    ]
};
