export const ROLES = {
    ADMIN: 'admin',
    DOCTOR: 'doctor',
    NURSE: 'nurse',
    RECEPTION: 'reception',
    PATIENT: 'patient',
    PHARMACIST: 'pharmacist',
    LAB_TECHNICIAN: 'lab_technician'
};

export const PERMISSIONS = {
    MANAGE_USERS: 'manage_users',
    MANAGE_PATIENTS: 'manage_patients',
    MANAGE_APPOINTMENTS: 'manage_appointments',
    VIEW_PATIENTS: 'view_patients',
    VIEW_APPOINTMENTS: 'view_appointments',
    MANAGE_PHARMACIES: 'manage_pharmacies',
    MANAGE_LABORATORIES: 'manage_laboratories',
    VIEW_PHARMACIES: 'view_pharmacies',
    VIEW_LABORATORIES: 'view_laboratories',
    MANAGE_CONSULTATIONS: 'manage_consultations',
    VIEW_CONSULTATIONS: 'view_consultations',
    MANAGE_PRESCRIPTIONS: 'manage_prescriptions',
    VIEW_PRESCRIPTIONS: 'view_prescriptions',
    MANAGE_LAB_ORDERS: 'manage_lab_orders',
    VIEW_LAB_ORDERS: 'view_lab_orders',
    PROCESS_LAB_ORDERS: 'process_lab_orders'
};

export const ROLE_PERMISSIONS = {
    [ROLES.ADMIN]: [
        PERMISSIONS.MANAGE_USERS,
        PERMISSIONS.MANAGE_PATIENTS,
        PERMISSIONS.MANAGE_APPOINTMENTS,
        PERMISSIONS.VIEW_PATIENTS,
        PERMISSIONS.VIEW_APPOINTMENTS,
        PERMISSIONS.MANAGE_PHARMACIES,
        PERMISSIONS.MANAGE_LABORATORIES,
        PERMISSIONS.VIEW_PHARMACIES,
        PERMISSIONS.VIEW_LABORATORIES,
        PERMISSIONS.MANAGE_CONSULTATIONS,
        PERMISSIONS.VIEW_CONSULTATIONS,
        PERMISSIONS.MANAGE_PRESCRIPTIONS,
        PERMISSIONS.VIEW_PRESCRIPTIONS,
        PERMISSIONS.MANAGE_LAB_ORDERS,
        PERMISSIONS.VIEW_LAB_ORDERS,
        PERMISSIONS.PROCESS_LAB_ORDERS
    ],
    [ROLES.DOCTOR]: [
        PERMISSIONS.MANAGE_PATIENTS,
        PERMISSIONS.MANAGE_APPOINTMENTS,
        PERMISSIONS.VIEW_PATIENTS,
        PERMISSIONS.VIEW_APPOINTMENTS,
        PERMISSIONS.MANAGE_CONSULTATIONS,
        PERMISSIONS.VIEW_CONSULTATIONS,
        PERMISSIONS.MANAGE_PRESCRIPTIONS,
        PERMISSIONS.VIEW_PRESCRIPTIONS,
        PERMISSIONS.MANAGE_LAB_ORDERS,
        PERMISSIONS.VIEW_LAB_ORDERS
    ],
    [ROLES.NURSE]: [
        PERMISSIONS.MANAGE_PATIENTS,
        PERMISSIONS.VIEW_PATIENTS,
        PERMISSIONS.VIEW_APPOINTMENTS,
        PERMISSIONS.VIEW_CONSULTATIONS,
        PERMISSIONS.VIEW_LAB_ORDERS
    ],
    [ROLES.RECEPTION]: [
        PERMISSIONS.MANAGE_APPOINTMENTS,
        PERMISSIONS.VIEW_APPOINTMENTS
    ],
    [ROLES.PATIENT]: [
        PERMISSIONS.VIEW_APPOINTMENTS,
        PERMISSIONS.VIEW_CONSULTATIONS,
        PERMISSIONS.VIEW_PRESCRIPTIONS,
        PERMISSIONS.VIEW_LAB_ORDERS
    ],
    [ROLES.PHARMACIST]: [
        PERMISSIONS.VIEW_PHARMACIES,
        PERMISSIONS.VIEW_PATIENTS, 
        PERMISSIONS.VIEW_PRESCRIPTIONS
    ],
    [ROLES.LAB_TECHNICIAN]: [
        PERMISSIONS.VIEW_LABORATORIES,
        PERMISSIONS.VIEW_PATIENTS,
        PERMISSIONS.VIEW_LAB_ORDERS,
        PERMISSIONS.PROCESS_LAB_ORDERS
    ]
};
